# Generated by Django 5.0.4 on 2024-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCommments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('comment', models.TextField()),
            ],
        ),
    ]
