# Generated by Django 5.0.4 on 2024-07-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipesCommments',
            new_name='RecipesComments',
        ),
    ]
